image: registry.gitlab.com/showcheap/android-ci:latest
before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew
cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches
build:
  stage: build
  script:
     - ./gradlew assemble --debug
test:
  stage: test
  script:
     - ./gradlew check